version: 0.2
#this buildspec assumes the ubuntu 14.04 trusty image
phases:
  install:
    commands:
      - sudo apt-get update -y
      - sudo apt-get update
      - sudo apt-get install clang cmake3 cppcheck clang-tidy-3.9 -y

  pre_build:
    commands:
      - export CC=clang
      - export CXX=clang++
  build:
    commands:
      - echo Build started on `date`
      - ./cppcheck.sh
      - mkdir build
      - cd build
      - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_SANITIZERS=ON ../
      - make
      - make test
      - cd ..
      - clang-tidy-3.9 -p=build **/*.c
  post_build:
    commands:
      - echo Build completed on `date`

