# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

UNWINDSET +=

CBMCFLAGS +=

EXPECTED = FAILED

HARNESS_ENTRY = cbmc_negative_tests_harness
HARNESS_FILE = $(HARNESS_ENTRY).c

PROOF_SOURCES += $(HARNESS_FILE)

PROJECT_SOURCES += $(HARNESS_FILE)

include ../Makefile.common
