version: 0.2
#this build spec assumes the ubuntu 14.04 trusty image
phases:
  install:
    commands:
      - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - sudo apt-get update -y
      - sudo apt-get install gcc-5 g++-5 cmake3 cppcheck -y
  pre_build:
    commands:
      - export CC=gcc-5
      - export CXX=g++-5
  build:
    commands:
      - echo Build started on `date`
      - ./cppcheck.sh
      - mkdir build
      - cd build
      - cmake ../
      - make
      - make test
  post_build:
    commands:
      - echo Build completed on `date`

