# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

###########
CBMCFLAGS +=

ENTRY = aws_is_power_of_two_harness
###########

include ../Makefile.common
