# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

###########
CBMCFLAGS +=

DEPENDENCIES += $(HELPERDIR)/stubs/error.c

ENTRY = aws_round_up_to_power_of_two_harness
###########

include ../Makefile.common
