# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

##########

# Sufficently long to get full coverage on the aws_byte_buf and aws_byte_cursor APIs
# short enough that all proofs complete in less than a minute
MAX_BUFFER_SIZE ?= 10

DEFINES += -DMAX_BUFFER_SIZE=$(MAX_BUFFER_SIZE)
