# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

################################################################
# This Makefile is the base makefile for CBMC proofs in this repository
# Consumers of this makefile are expected to set the relevant variables
# e.g. ENTRY, CBMCFLAGS, UNWINDSET etc
# and then include this makefile.  To see how to use this makefile, take a look
# at any of the existing proofs in this repository.
#
# This makefile is designed so that all files created during a proof are
# placed in the proof directory, or subdirectories of it.
# In particular, all gotos are built into the "gotos" folder, and logs go into
# the "logs" folder. This means that the main source directories are untouched by
# doing a build, and should make it safe to simultaniously build multiple proofs,
# including proofs with different configurations and -D defines.
#
# Dependency handling in this file may not be perfect.  It is recommended that
# you "make clean" or "make veryclean" before rerunning a proof.

SHELL=/bin/bash

default: report

# if Makefile.local exists, use it. This provides a way to override the defaults
sinclude Makefile.local

################################################################
# Define some constants that are hard to reference otherwise
SPACE :=$() $()
COMMA :=,

################################################################
# Useful macros
C_FROM_GOTO = $(patsubst $(GOTODIR)%,$(SRCDIR)%,$(1:.goto=.c))
GOTO_FROM_C = $(patsubst $(SRCDIR)%,$(GOTODIR)%,$(1:.c=.goto))
LOG_FROM_GOTO = $(patsubst $(GOTODIR)%,$(LOGDIR)%,$(1:.goto=.log))
LOG_FROM_ENTRY = $(LOGDIR)/$(notdir $(1:.goto=.log))
################################################################
# Setup paths to binaries
# By default, use the version on your path; this can be overriden to select particular
# versions of the tools. /usr/bin/goto-analyzer or ${HOME}/sw/goto-analyzer etc
GOTO_ANALYZER ?= goto-analyzer
GOTO_CC ?= goto-cc -Wall
GOTO_INSTRUMENT ?= goto-instrument
VIEWER ?= cbmc-viewer

################################################################
# Define locations and binaries
ABSTRACTIONS ?=

################################################################
# Default CBMC flags
CBMC_VERBOSITY ?=
CBMCFLAGS += --bounds-check
CBMCFLAGS += --conversion-check
CBMCFLAGS += --div-by-zero-check
CBMCFLAGS += --enum-range-check
CBMCFLAGS += --float-overflow-check
CBMCFLAGS += --nan-check
CBMCFLAGS += --pointer-check
CBMCFLAGS += --pointer-overflow-check
CBMCFLAGS += --pointer-primitive-check
CBMCFLAGS += --signed-overflow-check
CBMCFLAGS += --undefined-shift-check
CBMCFLAGS += --unsigned-overflow-check
CBMCFLAGS += --unwind 1
CBMCFLAGS += --unwinding-assertions

################################################################
# Preprocess the unwindset
ifneq ($(UNWINDSET),)
CBMC_UNWINDSET := --unwindset $(subst $(SPACE),$(COMMA),$(strip $(UNWINDSET)))
endif
CBMCFLAGS += $(CBMC_UNWINDSET)

################################################################
# Set C compiler defines
CBMC_OBJECT_BITS ?= 8
CBMCFLAGS +=  --object-bits $(CBMC_OBJECT_BITS)
DEFINES += -DCBMC_OBJECT_BITS=$(CBMC_OBJECT_BITS)
DEFINES += -DCBMC=1

################################################################
# Setup directory aliases
SRCDIR ?= $(abspath ../../..)
HELPERDIR ?= $(SRCDIR)/.cbmc-batch
PROOFDIR = $(abspath .)
GOTODIR = $(PROOFDIR)/gotos
LOGDIR = $(PROOFDIR)/logs

################################################################
# Setup include directory order
# HELPERDIR must go before any other includes to override default
# implementations by stubs
INC += -I$(HELPERDIR)/include/
INC += -I$(SRCDIR)/include/

################################################################
# Temporarily disable UNWIND_GOTO, SIMPLIFY until the feature is
# stable
UNWIND_GOTO ?= 0
SIMPLIFY ?= 0

################################################################
# Enables costly checks (e.g. ones that contain loops)
# Don't execute deep checks by default
AWS_DEEP_CHECKS ?= 0
DEFINES += -DAWS_DEEP_CHECKS=$(AWS_DEEP_CHECKS)

################################################################
# We always override allocator functions with our own allocator
# Removing the function from the goto program helps CBMC's
# function pointer analysis.
REMOVE_FUNCTION_BODY += --remove-function-body aws_default_allocator
REMOVE_FUNCTION_BODY += --remove-function-body s_cf_allocator_allocate
REMOVE_FUNCTION_BODY += --remove-function-body s_cf_allocator_copy_description
REMOVE_FUNCTION_BODY += --remove-function-body s_cf_allocator_deallocate
REMOVE_FUNCTION_BODY += --remove-function-body s_cf_allocator_preferred_size
REMOVE_FUNCTION_BODY += --remove-function-body s_cf_allocator_reallocate
REMOVE_FUNCTION_BODY += --remove-function-body s_default_calloc
REMOVE_FUNCTION_BODY += --remove-function-body s_default_free
REMOVE_FUNCTION_BODY += --remove-function-body s_default_malloc
REMOVE_FUNCTION_BODY += --remove-function-body s_default_realloc

################################################################
# We override abort() to be assert(0), as it is not caught by
# CBMC as a violation
ABSTRACTIONS += $(HELPERDIR)/stubs/abort_override_assert_false.c
REMOVE_FUNCTION_BODY += --remove-function-body abort
################################################################

REMOVE_FUNCTION_BODY += $(ADDITIONAL_REMOVE_FUNCTION_BODY)
DEPENDENT_GOTOS = $(call GOTO_FROM_C,$(DEPENDENCIES))
ENTRY_GOTO = $(GOTODIR)/$(ENTRY)

################################################################
# Other libraries that use this Makefile template may wish to do
# actual work here
setup_dependencies:
	echo "Setting up dependencies"

# Here, whenever there is a change in any of ANSI-C source
# dependency files, make will take action. However, to make
# sure changes in the headers files will also trigger make,
# the user must run make clean first.
$(ENTRY_GOTO)0.goto: setup_dependencies $(ENTRY).c $(DEPENDENT_GOTOS)
	mkdir -p $(dir $@)
	mkdir -p $(dir $(call LOG_FROM_ENTRY,$@))
	$(GOTO_CC) $(ENTRY).c \
	  --export-function-local-symbols $(CBMC_VERBOSITY) \
	  --function $(ENTRY) $(DEPENDENT_GOTOS) $(INC) $(DEFINES) -o $@ \
	  2>&1 | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}

# Removes specified function bodies. This allows us to replace
# function definitions with ABSTRACTIONS.
$(ENTRY_GOTO)1.goto: $(ENTRY_GOTO)0.goto
ifeq ($(REMOVE_FUNCTION_BODY),"")
	cp $< $@
	echo "Not removing function bodies" | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
else
	$(GOTO_INSTRUMENT) $(REMOVE_FUNCTION_BODY) $< $@ \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
endif

# ABSTRACTIONS is a list of function stubs to use. If a function body
# is missing and is not abstracted, then it returnes a non
# deterministic value.
$(ENTRY_GOTO)2.goto: $(ENTRY_GOTO)1.goto
ifeq ($(ABSTRACTIONS),"")
	cp $< $@
	echo "Not implementing abstractions" | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
else
	$(GOTO_CC) --function $(ENTRY) $(ABSTRACTIONS) $< $(INC) $(DEFINES) -o $@ \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@); exit $${PIPESTATUS[0]}
endif


## Temporarily skipped steps

# Simplify and constant propagation may benefit from unwinding first
$(ENTRY_GOTO)3.goto: $(ENTRY_GOTO)2.goto
ifeq ($(UNWIND_GOTO),1)
	$(GOTO_INSTRUMENT) $(UNWINDING) $< $@ \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
else
	cp $< $@
	echo "Not unwinding goto program" | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
endif

# Skip simplify (and hence generate-function-body) until missing source locations debugged
$(ENTRY_GOTO)4.goto: $(ENTRY_GOTO)3.goto
ifeq ($(SIMPLIFY),1)
	$(GOTO_INSTRUMENT) --generate-function-body '.*' $< $@ \
		2>&1 | tee$(call LOG_FROM_ENTRY,$@); exit $${PIPESTATUS[0]}
else
	cp $< $@
	echo "Not generating-function-bodies in goto program" | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
endif

# Skip simplify (and hence generate-function-body) until missing source locations debugged
$(ENTRY_GOTO)5.goto: $(ENTRY_GOTO)4.goto
ifeq ($(SIMPLIFY),1)
	$(GOTO_ANALYZER) --simplify $@ $< \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@); exit $${PIPESTATUS[0]}
else
	cp $< $@
	echo "Not simplfying goto program" | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}
endif

# Simplify the goto program by removing any unused function bodies
$(ENTRY_GOTO)6.goto: $(ENTRY_GOTO)5.goto
	$(GOTO_INSTRUMENT) --drop-unused-functions $< $@ \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}

# Simplify the goto program by slicing away initializations of unused
# global variables
$(ENTRY_GOTO)7.goto: $(ENTRY_GOTO)6.goto
	$(GOTO_INSTRUMENT) --slice-global-inits $< $@ \
		2>&1 | tee $(call LOG_FROM_ENTRY,$@) ; exit $${PIPESTATUS[0]}

$(ENTRY_GOTO).goto: $(ENTRY_GOTO)7.goto
	cp $< $@

# For now, CBMC batch expects the goto in the same folder as the proof itself,
# instead of the proof/gotos folder all other gotos go in.  This isn't a problem
# for out-of-tree or parallel builds, it just clutters the proof directory.
# I could update the .yaml file for all 160 proofs, or I could copy it, and
# have one goto file in the proof directory.  Doing the second option for now.
# TODO: cleanup which files go in which directories.
$(ENTRY).goto: $(ENTRY_GOTO).goto
	cp $< $@

# Catch-all used for building goto-binaries of the individual
# dependencies, which are then linked in the $(ENTRY_GOTO)0.goto rule above
# DSN TODO Make this depend on the correct thing.
%.goto:
	mkdir -p $(dir $@)
	mkdir -p $(dir $(call LOG_FROM_GOTO,$@))
	echo $(call C_FROM_GOTO,$@)
	$(GOTO_CC) -c $(call C_FROM_GOTO,$@) --export-function-local-symbols $(CBMC_VERBOSITY) \
	  $(INC) $(DEFINES) -o $@ \
	  2>&1 | tee $(call LOG_FROM_GOTO,$@) ; exit $${PIPESTATUS[0]}

goto: $(ENTRY).goto
	echo $(DEPENDENT_GOTOS)

cbmc.log: $(ENTRY).goto
	cbmc $(CBMCFLAGS) --trace $< 2>&1 | tee $@

property.xml: $(ENTRY).goto
	cbmc $(CBMCFLAGS) --show-properties --xml-ui $< 2>&1 > $@

coverage.xml: $(ENTRY).goto
	cbmc $(filter-out --unwinding-assertions,$(CBMCFLAGS)) --cover location --xml-ui $< 2>&1 > $@

cbmc: cbmc.log

property: property.xml

coverage: coverage.xml

report: cbmc.log property.xml coverage.xml
	$(VIEWER) \
	--block coverage.xml \
	--goto $(ENTRY).goto \
	--htmldir html \
	--property property.xml \
	--result cbmc.log \
	--srcdir $(SRCDIR) \
	--srcexclude "(./verification|./tests|./tools|./lib/third_party)"

clean:
	$(RM) *.goto
	$(RM) $(DEPENDENT_GOTOS)
	$(RM) *.log
	$(RM) cbmc.log property.xml coverage.xml TAGS
	$(RM) *~ \#*
	$(RM) -r gotos


veryclean: clean
	$(RM) -r html
	$(RM) -r logs

.PHONY: setup_dependencies cbmc property coverage report clean veryclean testdeps

PROOFDIR = $(abspath .)
PROOF_GOTOS = "$(PROOFDIR)/gotos"

DIRS = $(dir $(DEPENDENCIES))
GOTO_DIRS= $(patsubst $(SRCDIR)%,$(PROOF_GOTOS)%,$(DIRS))

include $(HELPERDIR)/jobs/Makefile.cbmc_batch
