# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

###########

CBMCFLAGS +=

HARNESS_ENTRY = aws_ptr_eq_harness
HARNESS_FILE = $(HARNESS_ENTRY).c

PROOF_SOURCES += $(HARNESS_FILE)

PROJECT_SOURCES += $(SRCDIR)/source/hash_table.c

###########

include ../Makefile.common
