# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0.

###########

CBMCFLAGS +=

DEPENDENCIES += $(SRCDIR)/source/hash_table.c

ENTRY = aws_ptr_eq_harness

###########

include ../Makefile.common
