name: Block needs-review merges

# Trigger on any push to non-main branches.
on:
  push:
    branches-ignore:
      - 'main'

permissions:
  pull-requests: read

jobs:
  gate:
    uses: awslabs/aws-crt-builder/.github/workflows/block-needs-review-label.yml@main
