name: Changelog Rollup
on:
  push:
    branches: [test/rollup-1.2.0]
jobs:
  rollup:
    permissions:
      contents: write
    uses: awslabs/aws-crt-builder/.github/workflows/changelog-rollup.yml@cl/7-workflows
    with:
      builder-ref: cl/7-workflows
      version: 1.2.0
      date: 2026-10-03
      minor-prs: '9010'
      release-branch: test-main
      docs-branch: test-docs
