name: Changelog Check
on:
  pull_request:
    branches: [test-main]
    types: [opened, edited, synchronize, reopened]
jobs:
  check:
    uses: awslabs/aws-crt-builder/.github/workflows/changelog-check.yml@cl/7-workflows
