name: Lint

on: [push]

jobs:
  clang-tidy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: clang-tidy lint
      run: |
        python3 -c "from urllib.request import urlretrieve; urlretrieve('https://d19elf31gohf1l.cloudfront.net/LATEST/builder.pyz?run=${{ env.RUN }}', 'builder')"
        chmod a+x builder
        ./builder clang-tidy --project=aws-c-common
