name: Lint

on: [push]

jobs:
  clang-tidy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: clang-tidy lint
      run: |
        python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
        chmod a+x builder
        ./builder clang-tidy
