name: Lint

on: [push]

jobs:
  clang-tidy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
