name: ClangASanUBSan

on: [push]

jobs:
  clang-tsan:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Sources
      uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        sudo apt-get install ninja-build
      
    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=clang -DCMAKE_C_FLAGS="-g" -DENABLE_SANITIZERS=ON -DSANITIZERS=",address,undefined" ..
        make
        make test
