name: Static

on: [push]

jobs:
  clang-static:
    runs-on: ubuntu-24.04

    steps:
      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Prepare build"
        run: |
          python3 -c "from urllib.request import urlretrieve; urlretrieve('https://d19elf31gohf1l.cloudfront.net/LATEST/builder.pyz?run=${{ env.RUN }}', 'builder')"
          chmod a+x builder
          ./builder clang-tidy --project=aws-c-common --cmake-extra=-DCMAKE_EXPORT_COMPILE_COMMANDS=ON

      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/compile_commands.json

      - uses: actions/upload-artifact@v4
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
