name: Static

on: [push]

env:
  BUILDER_VERSION: v0.9.74
  BUILDER_HOST: https://d19elf31gohf1l.cloudfront.net
  BUILDER_SOURCE: releases
  PACKAGE_NAME: aws-c-common
  CRT_CI_ROLE: ${{ secrets.CRT_CI_ROLE_ARN }}
  AWS_DEFAULT_REGION: us-east-1

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  clang-static:
    runs-on: ubuntu-24.04

    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.CRT_CI_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: "Check out repository"
        uses: actions/checkout@v4

      - name: "Prepare build"
        run: |
          python3 -c "from urllib.request import urlretrieve; urlretrieve('${{ env.BUILDER_HOST }}/${{ env.BUILDER_SOURCE }}/${{ env.BUILDER_VERSION }}/builder.pyz?run=${{ env.RUN }}', 'builder')"
          chmod a+x builder
          ./builder build -p ${{ env.PACKAGE_NAME }} --cmake-extra=-DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          ls build/aws-c-common

      - uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile: ${{ github.workspace }}/compile_commands.json

      - uses: actions/upload-artifact@v4
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}
